# Javascript Node CircleCI 2.0 configuration file
# Since every run step is a new shell, environment variables are not shared across steps. If you need an environment variable to be accessible in more than one step, export the value using BASH_ENV.

# CIRCLE_PREVIOUS_BUILD_NUM

version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.12.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - run : git show HEAD^$(echo $CIRCLE_PREVIOUS_BUILD_NUM)

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
  build_image:
    machine: true
    steps:
      - checkout
      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # build the application image
      - run: docker build -t 842750118asf7987/demo:$(echo $CIRCLE_SHA1 | cut -c1-7) .

      # deploy the image
      - run: docker push 842750118asf7987/demo:$(echo $CIRCLE_SHA1 | cut -c1-7)


  # - run:
  #         name: Deploy app to Digital Ocean Server via Docker
  #         command: |
  #           ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - test
      - build_image:
          filters:
            branches:
              only: master
      # - deploy:
      #     requires:
      #       - test
      #       - build_image
      #     filters:
      #       branches:
      #         only: master
